import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import styles from "../styles/home.module.css";
import { client } from "../pages/api/apolloClient";
import { getHomePageQuery } from "./api/contentful";
import { HomePageModel } from "../models/homePageModel";


type Props = {
    data: HomePageModel;
};

const Home = ({ data }: Props) => {
    console.log(data);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>Hello Workbuddy testing</h1>
            <p>{data.pageName}</p>
        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async () => {
    const { data, error } = await client.query({
        query: getHomePageQuery(),
    });

    console.log(data);
    return {
        props: {
            data: data.homePageCollection.items[0] as HomePageModel,
        },
    };
};

export default Home;